struct Casesolution {
settlementdate: chrono::NaiveDateTime,
runno: i32, 
intervention: i32, 
casesubtype: Option<String>, 							
solutionstatus: i32, 
spdversion: Option<String>, 							
nonphysicallosses: i32, 
totalobjective: f64, 
totalareagenviolation: f64,
totalinterconnectorviolation: f64,
totalgenericviolation: f64,
totalramprateviolation: f64,
totalunitmwcapacityviolation: f64, 
total5minviolation: f64, 							
totalregviolation: f64, 							
total6secviolation: f64, 							
total60secviolation: f64, 							
totalasprofileviolation: f64, 
totalfaststartviolation: f64, 	
totalenergyofferviolation: f64, 	
lastchanged: chrono::NaiveDateTime,
}