struct Constraint { 
    settlementdate: chrono::NaiveDateTime,
    runno: i64,
    constraintid: String, 
    dispatchinterval: i64, 
    intervention: i64, 
    rhs: f64, 
    marginalvalue: f64,
    violationdegree: f64, 
    lastchanged: chrono::NaiveDateTime,
    duid: String,						
    genconid_effectivedate: chrono::NaiveDateTime,
    genconid_versionno: i64, 
    lhs: f64, 
    settlementdate: chrono::NaiveDateTime,
    runno: i64, 
    constraintid: String, 
    dispatchinterval: i64, 
    intervention: i64, 
    rhs: f64, 
    marginalvalue: f64,
    violationdegree: f64, 
    lastchanged: chrono::NaiveDateTime,
}