struct PredispatchCaseSolution {
    predispatchseqno: String, 
    runno: i32, 
    solutionstatus: i32, 
    spdversion: String, 	
    nonphysicallosses: i32, 
    totalobjective: f64, 
    totalareagenviolation: f64, 
    totalinterconnectorviolation: f64, 
    totalgenericviolation: f64, 
    totalramprateviolation: f64, 
    totalunitmwcapacityviolation: f64, 
    total5minviolation: f64, 
    totalregviolation: f64, 
    total6secviolation: f64, 
    total60secviolation: f64, 
    totalasprofileviolation: f64, 
    totalenergyconstrviolation: f64, 
    totalenergyofferviolation: f64, 
    lastchanged: f64, 
    intervention: i32, 
}