struct PredispatchInterconnectorres { 
    predispatchseqno: String, 
    runno: i32, 
    interconnectorid: String, 
    periodid: String,
    intervention: i32, 
    meteredmwflow: f64, 
    mwflow: f64, 
    mwlosses: f64, 
    marginalvalue: f64, 
    violationdegree: f64, 
    lastchanged: chrono::NaiveDateTime,
    datetime: chrono::NaiveDateTime,
    exportlimit: f64, 
    importlimit: f64, 
    marginalloss: f64, 
    exportgenconid: String,
    importgenconid: String,
    fcasexportlimit: f64, 
    fcasimportlimit: f64, 
    local_price_adjustment_export: f64, 
    locally_constrained_export: i32, 
    local_price_adjustment_import: f64, 
    locally_constrained_import: i32, 
}