struct PredispatcConstraint { 
predispatchseqno: String, 
runno: i32, 
constraintid: String, 
periodid: String, 
intervention: i32, 
rhs: f64, 
marginalvalue: f64, 
violationdegree: f64, 
lastchanged: chrono::NaiveDateTime,
datetime: chrono::NaiveDateTime,
duid: String, 									
genconid_effectivedate: chrono::NaiveDateTime,
genconid_versionno: i64, 
lhs: f64, 
} 